# Generated by Django 5.2.16 on 2026-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان رویداد')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='شناسه متنی (Slug)')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('TOURNAMENT', 'تورنمنت'), ('WEBINAR', 'وبینار'), ('WORKSHOP', 'ورکشاپ'), ('SPORTS', 'ورزشی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشرشده'), ('CLOSED', 'بسته شده'), ('FINISHED', 'پایان\u200cیافته')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='تصویر بنر')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه/راند')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات جلسه')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب برگزاری')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع جلسه')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان جلسه')),
                ('stage_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت اختصاصی جلسه')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StageRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('role_type', models.CharField(choices=[('SPEAKER', 'سخنران'), ('JUDGE', 'داور'), ('COACH', 'مربی')], max_length=20, verbose_name='نوع نقش')),
            ],
        ),
    ]
