# Generated by Django 5.2.16 on 2026-07-21 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده'),
        ),
        migrations.AddField(
            model_name='eventstage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='event.event', verbose_name='رویداد مربوطه'),
        ),
        migrations.AddField(
            model_name='stagerole',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='event.eventstage', verbose_name='جلسه مربوطه'),
        ),
        migrations.AddField(
            model_name='stagerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterUniqueTogether(
            name='stagerole',
            unique_together={('stage', 'user', 'role_type')},
        ),
    ]
