# Generated by Django 5.2.16 on 2026-07-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattributevalue',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='event.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattributevalue',
            unique_together={('event', 'attribute')},
        ),
    ]
